version: "{build}"

clone_depth: 3

environment:
  BASEDIR: c:\mylibs
  SDLDIR: c:\mylibs\include\SDL2
  LIBDIR: c:\mylibs\lib

install:
  - mkdir %SDLDIR%
  - mkdir %LIBDIR%
  - IF NOT EXIST SDL2-devel-2.0.8-mingw.tar.gz curl -fsS -O https://libsdl.org/release/SDL2-devel-2.0.8-mingw.tar.gz
  - IF NOT EXIST SDL2_image-devel-2.0.3-mingw.tar.gz curl -fsS -O https://libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.3-mingw.tar.gz
  - IF NOT EXIST SDL2_mixer-devel-2.0.2-mingw.tar.gz curl -fsS -O https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.2-mingw.tar.gz
  - IF NOT EXIST SDL2_ttf-devel-2.0.14-mingw.tar.gz curl -fsS -O https://libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-mingw.tar.gz
  - copy SDL2-devel-2.0.8-mingw.tar.gz %TEMP% > nul
  - copy SDL2_image-devel-2.0.3-mingw.tar.gz %TEMP% > nul
  - copy SDL2_mixer-devel-2.0.2-mingw.tar.gz %TEMP% > nul
  - copy SDL2_ttf-devel-2.0.14-mingw.tar.gz %TEMP% > nul
  - cd %TEMP%
  - tar xf SDL2-devel-2.0.8-mingw.tar.gz > nul
  - tar xf SDL2_image-devel-2.0.3-mingw.tar.gz > nul
  - tar xf SDL2_mixer-devel-2.0.2-mingw.tar.gz > nul
  - tar xf SDL2_ttf-devel-2.0.14-mingw.tar.gz > nul
  - SDL2-2.0.8\i686-w64-mingw32\bin\sdl2-config --cflags --libs
  - copy SDL2-2.0.8\i686-w64-mingw32\include\SDL2\* %SDLDIR% > nul
  - copy SDL2_image-2.0.3\i686-w64-mingw32\include\SDL2\* %SDLDIR% > nul
  - copy SDL2_mixer-2.0.2\i686-w64-mingw32\include\SDL2\* %SDLDIR% > nul
  - copy SDL2_ttf-2.0.14\i686-w64-mingw32\include\SDL2\* %SDLDIR% > nul
  - copy SDL2-2.0.8\i686-w64-mingw32\lib\* %LIBDIR% > nul
  - copy SDL2_image-2.0.3\i686-w64-mingw32\lib\* %LIBDIR% > nul
  - copy SDL2_mixer-2.0.2\i686-w64-mingw32\lib\* %LIBDIR% > nul
  - copy SDL2_ttf-2.0.14\i686-w64-mingw32\lib\* %LIBDIR% > nul

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - c:\cygwin\bin\sh -lc ("cd /cygdrive/c/projects/pacman-sdl/; make LDFLAGS='-I/cygdrive/c/mylibs/include/SDL2 -I/cygdrive/c/mylibs/include -D_REENTRANT -L/cygdrive/c/mylibs/lib -lpthread -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lm'")

test: off
deploy: off

cache:
  - SDL2-devel-2.0.8-mingw.tar.gz
  - SDL2_image-devel-2.0.3-mingw.tar.gz
  - SDL2_mixer-devel-2.0.2-mingw.tar.gz
  - SDL2_ttf-devel-2.0.14-mingw.tar.gz
