version: "{build}"

clone_depth: 3

platform:
  - x86

environment:
  BASEDIR: c:\mylibs
  SDLDIR: c:\mylibs\include\SDL2
  LIBDIR: c:\mylibs\lib

install:
  - mkdir %SDLDIR%
  - mkdir %LIBDIR%
  - IF NOT EXIST SDL2-devel-2.0.8-VC.zip curl -fsS -O https://libsdl.org/release/SDL2-devel-2.0.8-VC.zip
  - IF NOT EXIST SDL2_image-devel-2.0.3-VC.zip curl -fsS -O https://libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.3-VC.zip
  - IF NOT EXIST SDL2_mixer-devel-2.0.2-VC.zip curl -fsS -O https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.2-VC.zip
  - IF NOT EXIST SDL2_ttf-devel-2.0.14-VC.zip curl -fsS -O https://libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-VC.zip
  - copy SDL2-devel-2.0.8-VC.zip %TEMP% > nul
  - copy SDL2_image-devel-2.0.3-VC.zip %TEMP% > nul
  - copy SDL2_mixer-devel-2.0.2-VC.zip %TEMP% > nul
  - copy SDL2_ttf-devel-2.0.14-VC.zip %TEMP% > nul
  - cd %TEMP%
  - 7z x SDL2-devel-2.0.8-VC.zip > nul
  - 7z x SDL2_image-devel-2.0.3-VC.zip > nul
  - 7z x SDL2_mixer-devel-2.0.2-VC.zip > nul
  - 7z x SDL2_ttf-devel-2.0.14-VC.zip > nul
  - copy SDL2-2.0.8\include\* %SDLDIR% > nul
  - copy SDL2_image-2.0.3\include\* %SDLDIR% > nul
  - copy SDL2_mixer-2.0.2\include\* %SDLDIR% > nul
  - copy SDL2_ttf-2.0.14\include\* %SDLDIR% > nul
  - copy SDL2-2.0.8\lib\x86\* %LIBDIR% > nul
  - copy SDL2_image-2.0.3\lib\x86\* %LIBDIR% > nul
  - copy SDL2_mixer-2.0.2\lib\x86\* %LIBDIR% > nul
  - copy SDL2_ttf-2.0.14\lib\x86\* %LIBDIR% > nul

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - c:\cygwin\bin\sh -lc ("cd /cygdrive/c/projects/pacman-sdl/; make LDFLAGS='-I/cygdrive/c/mylibs/include -Dmain=SDL_main -L/cygdrive/c/mylibs/lib -lpthread -mwindows -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lm'")

test: off
deploy: off

cache:
  - SDL2-devel-2.0.8-VC.zip
  - SDL2_image-devel-2.0.3-VC.zip
  - SDL2_mixer-devel-2.0.2-VC.zip
  - SDL2_ttf-devel-2.0.14-VC.zip
