version: "{build}"

clone_depth: 1

platform:
  - x86_64

install:
  - IF NOT EXIST SDL-1.2.15.tar.gz curl -fsS -O https://libsdl.org/release/SDL-1.2.15.tar.gz
  - tar xf SDL-1.2.15.tar.gz
  - c:\cygwin\bin\sh -lc ("CC=gcc CFLAGS=-I/usr/include/w32api; cd /cygdrive/c/projects/pacman-sdl/SDL-1.2.15; ./autogen.sh && ./configure && make && make install")
  - IF NOT EXIST SDL_mixer-1.2.12.tar.gz curl -fsS -O https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz
  - tar xf SDL_mixer-1.2.12.tar.gz
  - c:\cygwin\bin\sh -lc ("cd /cygdrive/c/projects/pacman-sdl/SDL_mixer-1.2.12; ./autogen.sh && ./configure && make && make install")
  - IF NOT EXIST SDL_image-1.2.12.tar.gz curl -fsS -O https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12.tar.gz
  - tar xf SDL_image-1.2.12.tar.gz
  - c:\cygwin\bin\sh -lc ("cd /cygdrive/c/projects/pacman-sdl/SDL_image-1.2.12; ./autogen.sh && ./configure && make && make install")

build_script:
  - make

test: off
deploy: off

cache:
  - SDL-1.2.15.tar.gz
  - SDL_image-1.2.12.tar.gz
  - SDL_mixer-1.2.12.tar.gz
