language: c++

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl sdl_image sdl_mixer; fi

script:
  - make

matrix:
  allow_failures:
    - osx

notifications:
  email:
    on_success: never
    on_failure: change
